--- #YAML:1.0
name:               DateTime-Format-Duration-XSD
version:            0.01
abstract:           Formats and parses DateTime::Duration
author:
    - Smal D A <nuf@frtk.ru>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0.3
    DateTime::Format::Duration:  1.03
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
